[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm next build', 'pnpm tsup src/server.ts --format esm --platform node --target node20 --out-dir dist --no-splitting --no-minify']

[start]
cmd = 'node dist/server.js'
